### ISSUE TITLE
Decrease arrow count as soon as it is released

### ISSUE THREAD

**Issue by swapagarwal** [swapagarwal/bunnies-and-badgers#8]
Right now, the arrow count is decreased when it goes out of screen. It should ideally be decreased as soon as the arrow is released.
Spoiler: Move the logic from [here](https://github.com/swapagarwal/bunnies-and-badgers/blob/master/Bunnies%26Badgers.py#L80) to [there](https://github.com/swapagarwal/bunnies-and-badgers/blob/master/Bunnies%26Badgers.py#L166).

**Comment by saurabh-kumar-vit** [comment]
I would like to take up this issue, if it is still available.

**Comment by swapagarwal** [comment]
@saurabh-kumar-vit Sure, go ahead! 😄

**Comment by saurabh-kumar-vit** [comment]
I have started a PR for this issue. Please review it.
